ebs-time: time/cron.c File Reference
cron.c File Reference
Cron-like scheduling framework implementations.
#include "cron.h"
Functions
void tm_cron_init (void)
void tm_cron_clear_job (cron_job_t *job_p)
void tm_cron_create_job_abs (cron_job_t *job_p, void handler(void), tm_system_t *texec_p, tm_sdelta_t *tafter_p)
void tm_cron_create_job_rel (cron_job_t *job_p, void handler(void), tm_sdelta_t *trelexec_p, tm_sdelta_t *tafter_p)
void tm_cron_insert_job (cron_job_t *job_p)
void tm_cron_cancel_job (cron_job_t *job_p)
void tm_cron_poll (void)
void tm_cron_epoch_change_handler (tm_sdelta_t *offset)
Variables
cron_job_t * cron_nextjob_p = NULL
tm_epochchange_handler_t cron_change_handler = {NULL, 3, &tm_cron_epoch_change_handler}
Detailed Description
Cron-like scheduling framework implementations.
See also
cron.h
Definition in file cron.c.
Function Documentation
tm_cron_cancel_job()
void tm_cron_cancel_job (cron_job_t * job_p)
Definition at line 111 of file cron.c.
References CRON_JOB_t::active, cron_nextjob_p, CRON_JOB_t::nextjob, and CRON_JOB_t::prevjob.
Referenced by tm_cron_clear_job(), and tm_cron_replace_job().
tm_cron_clear_job()
void tm_cron_clear_job (cron_job_t * job_p)
Definition at line 44 of file cron.c.
References CRON_JOB_t::active, CRON_JOB_t::handler, CRON_JOB_t::nextjob, CRON_JOB_t::prevjob, CRON_JOB_t::tafter_p, CRON_JOB_t::texec, and tm_cron_cancel_job().
tm_cron_create_job_abs()
void tm_cron_create_job_abs (cron_job_t * job_p, void handlervoid, tm_system_t * texec_p, tm_sdelta_t * tafter_p)
Definition at line 55 of file cron.c.
References CRON_JOB_t::handler, CRON_JOB_t::tafter_p, CRON_JOB_t::texec, and tm_cron_insert_job().
tm_cron_create_job_rel()
void tm_cron_create_job_rel (cron_job_t * job_p, void handlervoid, tm_sdelta_t * trelexec_p, tm_sdelta_t * tafter_p)
Definition at line 65 of file cron.c.
References CRON_JOB_t::handler, CRON_JOB_t::tafter_p, CRON_JOB_t::texec, tm_apply_sdelta(), tm_cron_insert_job(), and tm_current_time().
tm_cron_epoch_change_handler()
void tm_cron_epoch_change_handler (tm_sdelta_t * offset)
Definition at line 149 of file cron.c.
References cron_nextjob_p, CRON_JOB_t::nextjob, CRON_JOB_t::texec, and tm_apply_sdelta().
tm_cron_init()
void tm_cron_init (void)
Definition at line 39 of file cron.c.
References cron_change_handler, and tm_register_epoch_change_handler().
Referenced by tm_init().
tm_cron_insert_job()
void tm_cron_insert_job (cron_job_t * job_p)
Definition at line 76 of file cron.c.
References CRON_JOB_t::active, cron_nextjob_p, CRON_JOB_t::nextjob, CRON_JOB_t::prevjob, CRON_JOB_t::texec, and tm_cmp_stime().
Referenced by tm_cron_create_job_abs(), tm_cron_create_job_rel(), and tm_cron_replace_job().
tm_cron_poll()
void tm_cron_poll (void)
Definition at line 126 of file cron.c.
References CRON_JOB_t::active, cron_nextjob_p, CRON_JOB_t::handler, CRON_JOB_t::nextjob, CRON_JOB_t::prevjob, CRON_JOB_t::tafter_p, CRON_JOB_t::texec, tm_apply_sdelta(), tm_cmp_stime(), tm_cron_replace_job(), and tm_current_time().
Variable Documentation
cron_change_handler
tm_epochchange_handler_t cron_change_handler = {NULL, 3, &tm_cron_epoch_change_handler}
Definition at line 36 of file cron.c.
Referenced by tm_cron_init().
cron_nextjob_p
cron_job_t* cron_nextjob_p = NULL
Definition at line 34 of file cron.c.
Referenced by tm_cron_cancel_job(), tm_cron_epoch_change_handler(), tm_cron_insert_job(), and tm_cron_poll().