ebs-time: time/time.h File Reference
time.h File Reference
Time related functions for embebedded systems.
#include <stdint.h>
#include <string.h>
#include "config.h"
#include <platform/cpu.h>
#include <ucdm/ucdm.h>
Data Structures
struct TM_REAL_t
Real Time Storage Type.
struct TM_RDELTA_t
Real Timedelta Storage Type.
struct TM_EPOCH_CHANGEHANDLER_t
Epoch Change Handler Type.
Macros
Time Tick Calculations
These definitions configure the systick and prepare all the calculated names derived from it.
This definition is informational only. Changing this number could have insidious consequences.
#define TIME_SYSTICK_PERIOD_uS 1000
#define TIME_TICKS_PER_SECOND (int32_t)(1000000 / TIME_SYSTICK_PERIOD_uS)
#define TIME_TICKS_PER_MINUTE (TIME_TICKS_PER_SECOND * 60)
#define TIME_TICKS_PER_HOUR (TIME_TICKS_PER_MINUTE * 60)
#define TIME_TICKS_PER_DAY (TIME_TICKS_PER_HOUR * 24)
#define TIME_SECONDS_PER_MINUTE (int32_t)(60)
#define TIME_SECONDS_PER_HOUR (TIME_SECONDS_PER_MINUTE * 60)
#define TIME_SECONDS_PER_DAY (TIME_SECONDS_PER_HOUR * 24)
Functions
Time Initialization and Maintenance Functions
ucdm_addr_t tm_init (ucdm_addr_t ucdm_address)
Intitialize time library constructs.
void tm_install_descriptor (void)
Install the time library descriptor to the application.
void tm_clear_stime (tm_system_t *stime)
Clear a tm_system_t instance.
void tm_clear_sdelta (tm_sdelta_t *sdelta)
Clear a tm_sdelta_t instance.
void tm_clear_rtime (tm_real_t *rtime)
Clear a tm_real_t instance.
void tm_clear_rdelta (tm_rdelta_t *rdelta)
Clear a tm_rdelta_t instance.
uint8_t tm_check_invalid_rtime (tm_real_t *rtime)
Validate a tm_real_t instance.
Basic Time Manipulation Functions
Basic time information manipulation functions. Use these whenever possible, and resort to using the (higher level) Real time manipulation functions only when it's really necessary.
static void tm_current_time (tm_system_t *stime)
Get the current system time.
static int8_t tm_cmp_stime (tm_system_t *t1, tm_system_t *t2)
static void tm_get_sdelta (tm_system_t *t1, tm_system_t *t2, tm_sdelta_t *sdelta)
Get the difference between two system times as a system time delta (t2 - t1)
static void tm_apply_sdelta (tm_system_t *t, tm_sdelta_t *sdelta)
Apply a time difference to a time in system time.
Real Time Manipulation Functions
Functions to manipule Real time. Use these functions sparingly, and usually only when dealing with user-generated or externally generated information. The further down this group of functions you go, the worse it's going to get.
void tm_sdelta_from_rdelta (tm_rdelta_t *rdelta, tm_sdelta_t *sdelta)
Convert a tm_rdelta_t instance into systick units.
void tm_rdelta_from_sdelta (tm_sdelta_t *sdelta, tm_rdelta_t *rdelta)
Convert a time difference in systick units into a real time difference.
static void tm_apply_rdelta (tm_system_t *t, tm_rdelta_t *rdelta)
Apply a real time difference to a time in systick units.
void tm_stime_from_rtime (tm_real_t *rtime, tm_system_t *stime)
Get a system timestamp from a real time, against the current epoch.
void tm_rtime_from_stime (tm_system_t *stime, tm_real_t *rtime)
Get the real time from a system timestamp against the current epoch.
Epoch Manipulation Functions
Functions to manipule the Epoch. These functions should be avoided in all but the most demanding of applications. The default configuration of the library uses the Unix Epoch.
Variable Epochs will most likely be useful in cases where a second time reference is maintained relative to the primary Epoch. This type of use is not currently supported by this library, since tm_epoch is a global which is used by a number of functions. Passing tm_epoch around is going to make it far more expensive than it already is.
These implementations are here for the sake of completeness. If you don't actually used the functions, the compiler will get rid of them.
In the future, it may be possible to adapt these implementations to provide one or more of the following :
A variable epoch operating alongside a high resolution system clock. The high resolution of the clock will shorten the epoch validity for the same size of the clock.
Allow the use of these functions to maintain secondary / multiple epochs. An example use case could be the maintenance of TLE Epochs.
void tm_set_epoch (tm_real_t *rtime, uint8_t follow)
Set the epoch time from an external real time source.
void tm_register_epoch_change_handler (tm_epochchange_handler_t *handler)
Register a callback for changes to the epoch.
Variables
Time Containers
These containers are defined internally in the library.
volatile tm_system_t tm_current
tm_real_t tm_epoch
int8_t tm_leapseconds
tm_real_t tm_internal_epoch
int64_t tm_internal_epoch_offset
uint8_t use_epoch
tm_epochchange_handler_t * epoch_handlers_root
Time Types
Various type definitions related to time storage and exchange.
#define TM_REAL_t_DEFINED
typedef int64_t tm_system_t
System Time Storage Type.
typedef int64_t tm_sdelta_t
System Timedelta Storage Type.
typedef struct TM_REAL_t tm_real_t
Real Time Storage Type.
typedef struct TM_RDELTA_t tm_rdelta_t
Real Timedelta Storage Type.
typedef struct TM_EPOCH_CHANGEHANDLER_t tm_epochchange_handler_t
Epoch Change Handler Type.
Detailed Description
Time related functions for embebedded systems.
While this library uses int64_t with the intent to support negative timestamps, most functions would do not support this and will break.
This library uses the following UCDM registers:
Base Address: TIME_BASE_ADDRESS
System Time is the current time of the device. This is returned directly from the system time in the same format, ie, int64_t.
Address Description Access Type
0 System Time, Register 0 Read, Pointer
1 System Time, Register 1 Read, Pointer
2 System Time, Register 2 Read, Pointer
3 System Time, Register 3 Read, POinter
If synchronization is enabled by TIME_ENABLE_SYNC, the following additional registers are used
Address Description Access Type
4 System Time Read Hook Read, Func
5 Reserved None
6 Time Sync Register 1 Write
7 Time Sync Register 2 Write
8 Time Sync Register 3 Write
9 Time Sync Register 4 Write, Handle
This library provides the following descriptors:
DESCRIPTOR_TAG_LIBVERSION : Time Library Version, per EBS version format DESCRIPTOR_TAG_TIME_EPOCH : Configured Epoch Time
See also
time.c
Definition in file time.h.
Data Structure Documentation
TM_REAL_t
struct TM_REAL_t
Real Time Storage Type.
This (struct) type stores a 'real' time. This type does not depend on the epoch and is independent of system time.
This form of time storage is always going to be expensive, and should therefore be used sparingly.
This type is not time-zone aware, and should always be interpreted as UTC time (GMT+0000). See the documentation of time.h for further detail about the interpretation of time by this library.
This library does no implicit validation of the data provided, and values outside expected ranges of each component of the real time can cause unexpected behaviour and crashes. If applications use uexternal or unsanitized sources to initizalize this type, then the application must also validate the input. One option to do so would be to initialize the tm_real_t and then use tm_check_invalid_rtime().
Definition at line 156 of file time.h.
Data Fields
uint8_t century
uint8_t date
uint8_t hours
uint16_t millis
uint8_t minutes
uint8_t month
uint8_t seconds
uint8_t year
TM_RDELTA_t
struct TM_RDELTA_t
Real Timedelta Storage Type.
This (struct) type stores a 'real' time difference.
This form of time storage is always going to be expensive, and should therefore be used sparingly.
Definition at line 178 of file time.h.
Data Fields
uint16_t days
uint8_t hours
uint16_t millis
uint8_t minutes
uint8_t seconds
uint8_t sgn
Macro Definition Documentation
TIME_SECONDS_PER_DAY
#define TIME_SECONDS_PER_DAY (TIME_SECONDS_PER_HOUR * 24)
Definition at line 98 of file time.h.
TIME_SECONDS_PER_HOUR
#define TIME_SECONDS_PER_HOUR (TIME_SECONDS_PER_MINUTE * 60)
Definition at line 97 of file time.h.
TIME_SECONDS_PER_MINUTE
#define TIME_SECONDS_PER_MINUTE (int32_t)(60)
Definition at line 96 of file time.h.
TIME_SYSTICK_PERIOD_uS
#define TIME_SYSTICK_PERIOD_uS 1000
Definition at line 89 of file time.h.
TIME_TICKS_PER_DAY
#define TIME_TICKS_PER_DAY (TIME_TICKS_PER_HOUR * 24)
Definition at line 94 of file time.h.
TIME_TICKS_PER_HOUR
#define TIME_TICKS_PER_HOUR (TIME_TICKS_PER_MINUTE * 60)
Definition at line 93 of file time.h.
TIME_TICKS_PER_MINUTE
#define TIME_TICKS_PER_MINUTE (TIME_TICKS_PER_SECOND * 60)
Definition at line 92 of file time.h.
TIME_TICKS_PER_SECOND
#define TIME_TICKS_PER_SECOND (int32_t)(1000000 / TIME_SYSTICK_PERIOD_uS)
Definition at line 91 of file time.h.
TM_REAL_t_DEFINED
#define TM_REAL_t_DEFINED
Definition at line 133 of file time.h.
Typedef Documentation
tm_epochchange_handler_t
typedef struct TM_EPOCH_CHANGEHANDLER_t tm_epochchange_handler_t
Epoch Change Handler Type.
This (struct) type stores an epoch change handler, and must be instantiated and registered by consumers requiring epoch change notifications.
Generally, an epoch change should be considered a rare occurence. If an application is expecting epoch changes, then the application can use the time delta provided to the handler to shift any stored timestamps to the new epoch. This remains largely untested.
If the epoch change is not to be followed, then the change handler will be provided 0 as the time delta. In such cases, applications must discard any stored timestamps. This usually would happen if the two epochs are fundamentally incompatible, or if the change involves more than just a shift in the epoch.
Note that epoch change handlers are run in an interrupt-disabled context, so they should be as quick as possible.
The epoch change handlers should be called in increasing order of the priority member, and this could, in principle, be used by the application to sequence shifts of related timestamps. This is not implemented.
tm_rdelta_t
typedef struct TM_RDELTA_t tm_rdelta_t
Real Timedelta Storage Type.
This (struct) type stores a 'real' time difference.
This form of time storage is always going to be expensive, and should therefore be used sparingly.
tm_real_t
typedef struct TM_REAL_t tm_real_t
Real Time Storage Type.
This (struct) type stores a 'real' time. This type does not depend on the epoch and is independent of system time.
This form of time storage is always going to be expensive, and should therefore be used sparingly.
This type is not time-zone aware, and should always be interpreted as UTC time (GMT+0000). See the documentation of time.h for further detail about the interpretation of time by this library.
This library does no implicit validation of the data provided, and values outside expected ranges of each component of the real time can cause unexpected behaviour and crashes. If applications use uexternal or unsanitized sources to initizalize this type, then the application must also validate the input. One option to do so would be to initialize the tm_real_t and then use tm_check_invalid_rtime().
tm_sdelta_t
typedef int64_t tm_sdelta_t
System Timedelta Storage Type.
This type stores a 'system' time difference.
The least count is based on the least count created by the system tick, and is expected to be 1ms.
Definition at line 130 of file time.h.
tm_system_t
typedef int64_t tm_system_t
System Time Storage Type.
A signed int64_t type, stores a 'system' time as number of milliseconds since the epoch.
The least count is based on the least count created by the system tick, and is expected to be 1ms.
Definition at line 119 of file time.h.
Function Documentation
tm_apply_rdelta()
static void tm_apply_rdelta (tm_system_t * t, tm_rdelta_t * rdelta) inline static
Apply a real time difference to a time in systick units.
Parameters
t Pointer to (a copy of) the original timestamp. This will be overwritten.
rdelta Pointer to the tm_rdelta_t in which the desired difference is stored.
Definition at line 415 of file time.h.
References tm_apply_sdelta(), and tm_sdelta_from_rdelta().
tm_apply_sdelta()
static void tm_apply_sdelta (tm_system_t * t, tm_sdelta_t * sdelta) inline static
Apply a time difference to a time in system time.
Parameters
t Pointer to (a copy of) the original timestamp. This will be overwritten.
sdelta Pointer to the time difference to apply
Definition at line 372 of file time.h.
Referenced by tm_apply_rdelta(), tm_cron_create_job_rel(), tm_cron_epoch_change_handler(), tm_cron_poll(), and tm_set_epoch().
tm_check_invalid_rtime()
uint8_t tm_check_invalid_rtime (tm_real_t * rtime)
Validate a tm_real_t instance.
Returns 0 for valid tm_real_t, non-zero for out of bounds.
Parameters
rtime Pointer to the tm_rtime_t to validate.
Definition at line 134 of file time.c.
References TM_REAL_t::century, TM_REAL_t::date, TM_REAL_t::hours, TM_REAL_t::millis, TM_REAL_t::minutes, TM_REAL_t::month, TM_REAL_t::seconds, and TM_REAL_t::year.
tm_clear_rdelta()
void tm_clear_rdelta (tm_rdelta_t * rdelta)
Clear a tm_rdelta_t instance.
Parameters
rdelta Pointer to the time_delta_t to clear.
Definition at line 124 of file time.c.
References TM_RDELTA_t::days, TM_RDELTA_t::hours, TM_RDELTA_t::millis, TM_RDELTA_t::minutes, TM_RDELTA_t::seconds, and TM_RDELTA_t::sgn.
Referenced by tm_rdelta_from_sdelta().
tm_clear_rtime()
void tm_clear_rtime (tm_real_t * rtime)
Clear a tm_real_t instance.
Parameters
rtime Pointer to the time_real_t to clear.
Definition at line 112 of file time.c.
References TM_REAL_t::century, TM_REAL_t::date, TM_REAL_t::hours, TM_REAL_t::millis, TM_REAL_t::minutes, TM_REAL_t::month, TM_REAL_t::seconds, and TM_REAL_t::year.
tm_clear_sdelta()
void tm_clear_sdelta (tm_sdelta_t * sdelta)
Clear a tm_sdelta_t instance.
Parameters
sdelta Pointer to the time_sdelta_t to clear.
Definition at line 107 of file time.c.
Referenced by tm_set_epoch().
tm_clear_stime()
void tm_clear_stime (tm_system_t * stime)
Clear a tm_system_t instance.
Parameters
stime Pointer to the tm_system_t to clear.
Definition at line 102 of file time.c.
Referenced by tm_set_epoch().
tm_cmp_stime()
static int8_t tm_cmp_stime (tm_system_t * t1, tm_system_t * t2) inline static
Definition at line 337 of file time.h.
Referenced by tm_cron_insert_job(), and tm_cron_poll().
tm_current_time()
static void tm_current_time (tm_system_t * stime) inline static
Get the current system time.
Parameters
stime Pointer to the location where the current system timestamp should be copied to.
Definition at line 328 of file time.h.
References tm_current.
Referenced by tm_cron_create_job_rel(), and tm_cron_poll().
tm_get_sdelta()
static void tm_get_sdelta (tm_system_t * t1, tm_system_t * t2, tm_sdelta_t * sdelta) inline static
Get the difference between two system times as a system time delta (t2 - t1)
Note that both times must be against the same epoch time.
Parameters
t1 Pointer to the first timestamp (*tm_system_t)
t2 Pointer to the second timestamp (*tm_system_t)
sdelta Poiter to the location where the delta should be stored
Definition at line 359 of file time.h.
Referenced by tm_set_epoch().
tm_init()
ucdm_addr_t tm_init (ucdm_addr_t ucdm_address)
Intitialize time library constructs.
The address provided to this function will be called TIME_BASE_ADDRESS for the purposes of this library, though EBS applications using the devicemap may choose to call it DMAP_TIME_BASE_ADDRESS instead. All other UCDM addresses discussed in this library will be referenced to this base address unless otherwise specified.
Definition at line 75 of file time.c.
References tm_cron_init(), tm_current, tm_epoch_descriptor, tm_install_descriptor(), tm_systick_init(), and TM_UCDM_STIME_LEN.
tm_install_descriptor()
void tm_install_descriptor (void)
Install the time library descriptor to the application.
The time application descriptor contains the library version number and is installed to the application descriptors with the tag specified in UCDM's descriptor header as DESCRIPTOR_TAG_LIBVERSION.
This does not effect the functionality of the time library in any way.
Referenced by tm_init().
tm_rdelta_from_sdelta()
void tm_rdelta_from_sdelta (tm_sdelta_t * sdelta, tm_rdelta_t * rdelta)
Convert a time difference in systick units into a real time difference.
Parameters
sdelta Pointer to the time difference in system time units.
rdelta Pointer to the tm_rdelta_t in which to store the result.
Definition at line 178 of file time.c.
References TM_RDELTA_t::days, TM_RDELTA_t::hours, TM_RDELTA_t::millis, TM_RDELTA_t::minutes, TM_RDELTA_t::seconds, TM_RDELTA_t::sgn, TIME_SECONDS_PER_DAY, TIME_SECONDS_PER_HOUR, TIME_SECONDS_PER_MINUTE, and tm_clear_rdelta().
tm_register_epoch_change_handler()
void tm_register_epoch_change_handler (tm_epochchange_handler_t * handler)
Register a callback for changes to the epoch.
Use this if you are storing timestamps for any reason. If possible, invalidate your stored timestamps. If you need to retain that information, apply the provided delta.
If the change is not intended to be followed, the delta reported will be zero. In this case, the function should discard all timestamp information.
Note
This function should also be used to follow time sync where applicable.
Parameters
handler Pointer to the epoch change handler.
Definition at line 392 of file time.c.
References epoch_handlers_root.
Referenced by tm_cron_init().
tm_rtime_from_stime()
void tm_rtime_from_stime (tm_system_t * stime, tm_real_t * rtime)
Get the real time from a system timestamp against the current epoch.
If the current epoch is not set, does nothing.
Note
NOT IMPLEMENTED YET!
Todo:
Align to gmtime
Parameters
stime The system time (as a pointer to a tm_system_t instance)
rtime Pointer to the tm_real_t in which to store the result. represented by stime.
Definition at line 262 of file time.c.
References TM_REAL_t::century, TM_REAL_t::date, days_in_month, gyear(), TM_REAL_t::hours, TM_REAL_t::millis, TM_REAL_t::minutes, TM_REAL_t::month, TM_REAL_t::seconds, TIME_SECONDS_PER_DAY, TIME_SECONDS_PER_HOUR, TIME_SECONDS_PER_MINUTE, tm_internal_epoch, tm_internal_epoch_offset, tm_leapseconds, use_epoch, and TM_REAL_t::year.
tm_sdelta_from_rdelta()
void tm_sdelta_from_rdelta (tm_rdelta_t * rdelta, tm_sdelta_t * sdelta)
Convert a tm_rdelta_t instance into systick units.
Parameters
rdelta Pointer to the time difference in real time units.
sdelta Pointer to the tm_sdelta_t in which to store the result.
Definition at line 165 of file time.c.
References TM_RDELTA_t::days, TM_RDELTA_t::hours, TM_RDELTA_t::millis, TM_RDELTA_t::minutes, TM_RDELTA_t::seconds, TM_RDELTA_t::sgn, TIME_SECONDS_PER_DAY, TIME_SECONDS_PER_HOUR, and TIME_SECONDS_PER_MINUTE.
Referenced by tm_apply_rdelta().
tm_set_epoch()
void tm_set_epoch (tm_real_t * rtime, uint8_t follow)
Set the epoch time from an external real time source.
Note that for 'follow' to work, both the new epoch and the old one should be representable against the old epoch.
Because this function touches timestamps across the system, and the time variables are likely in an inconsistent state over the course of this operation, this function disables interrupts.
Parameters
rtime Pointer to the time_real_t in which the desired epoch is stored
follow Whether the system should try to adjust stored timestamps to the new epoch.
Definition at line 357 of file time.c.
References epoch_handlers_root, TM_EPOCH_CHANGEHANDLER_t::next, tm_apply_sdelta(), tm_clear_sdelta(), tm_clear_stime(), tm_current, tm_epoch, tm_get_sdelta(), tm_internal_epoch_offset, tm_set_internal_epoch(), tm_stime_from_rtime(), and use_epoch.
tm_stime_from_rtime()
void tm_stime_from_rtime (tm_real_t * rtime, tm_system_t * stime)
Get a system timestamp from a real time, against the current epoch.
If the current epoch is not set, returns 0. Currently only supports epochs with frac = 0.
Todo:
Align to timegm.
Parameters
rtime The real time (as a pointer to a tm_real_t instance)
stime Pointer to the tm_system_t in which to store the result.
Definition at line 216 of file time.c.
References TM_REAL_t::date, days_to_month, gyear(), TM_REAL_t::hours, TM_REAL_t::millis, TM_REAL_t::minutes, TM_REAL_t::month, TM_REAL_t::seconds, TIME_SECONDS_PER_DAY, TIME_SECONDS_PER_HOUR, TIME_SECONDS_PER_MINUTE, tm_internal_epoch, tm_internal_epoch_offset, tm_leapseconds, and use_epoch.
Referenced by tm_set_epoch().
Variable Documentation
epoch_handlers_root
tm_epochchange_handler_t* epoch_handlers_root extern
Definition at line 51 of file time.c.
Referenced by tm_register_epoch_change_handler(), and tm_set_epoch().
tm_current
volatile tm_system_t tm_current extern
Referenced by time_systick_handler(), tm_current_time(), tm_init(), and tm_set_epoch().
tm_epoch
tm_real_t tm_epoch extern
Definition at line 45 of file time.c.
Referenced by tm_set_epoch().
tm_internal_epoch
tm_real_t tm_internal_epoch extern
Definition at line 46 of file time.c.
Referenced by tm_rtime_from_stime(), tm_set_internal_epoch(), and tm_stime_from_rtime().
tm_internal_epoch_offset
int64_t tm_internal_epoch_offset extern
Definition at line 47 of file time.c.
Referenced by tm_rtime_from_stime(), tm_set_epoch(), tm_set_internal_epoch(), and tm_stime_from_rtime().
tm_leapseconds
int8_t tm_leapseconds extern
Definition at line 49 of file time.c.
Referenced by tm_rtime_from_stime(), and tm_stime_from_rtime().
use_epoch
uint8_t use_epoch extern
Definition at line 48 of file time.c.
Referenced by tm_rtime_from_stime(), tm_set_epoch(), and tm_stime_from_rtime().