ebs-time: time/time.c File Reference
time.c File Reference
Time related function implementations.
#include <ds/sllist.h>
#include <ucdm/descriptor.h>
#include <string.h>
#include "time.h"
#include "systick.h"
#include "sync.h"
#include "cron.h"
#include <platform/sections.h>
Macros
#define TM_UCDM_STIME_LEN (sizeof(tm_system_t) / 2 + (sizeof(tm_system_t) % 2 != 0))
#define TM_UCDM_RTIME_LEN (sizeof(tm_real_t) / 2 + (sizeof(tm_real_t) % 2 != 0))
Functions
ucdm_addr_t tm_init (ucdm_addr_t ucdm_address)
Intitialize time library constructs.
void tm_clear_stime (tm_system_t *stime)
Clear a tm_system_t instance.
void tm_clear_sdelta (tm_sdelta_t *sdelta)
Clear a tm_sdelta_t instance.
void tm_clear_rtime (tm_real_t *rtime)
Clear a tm_real_t instance.
void tm_clear_rdelta (tm_rdelta_t *rdelta)
Clear a tm_rdelta_t instance.
uint8_t tm_check_invalid_rtime (tm_real_t *rtime)
Validate a tm_real_t instance.
void tm_sdelta_from_rdelta (tm_rdelta_t *rdelta, tm_sdelta_t *sdelta)
Convert a tm_rdelta_t instance into systick units.
void tm_rdelta_from_sdelta (tm_sdelta_t *sdelta, tm_rdelta_t *rdelta)
Convert a time difference in systick units into a real time difference.
void tm_stime_from_rtime (tm_real_t *rtime, tm_system_t *stime)
Get a system timestamp from a real time, against the current epoch.
void tm_rtime_from_stime (tm_system_t *stime, tm_real_t *rtime)
Get the real time from a system timestamp against the current epoch.
void tm_set_epoch (tm_real_t *rtime, uint8_t follow)
Set the epoch time from an external real time source.
void tm_register_epoch_change_handler (tm_epochchange_handler_t *handler)
Register a callback for changes to the epoch.
Variables
volatile tm_system_t tm_current FASTDATA
tm_real_t tm_epoch = {19, 70, 1, 1, 0, 0, 0, 0}
tm_real_t tm_internal_epoch = {19, 69, 3, 1, 0, 0, 0, 0}
int64_t tm_internal_epoch_offset = 26438400 * 1000LL
uint8_t use_epoch = 1
int8_t tm_leapseconds = 0
tm_epochchange_handler_t * epoch_handlers_root = NULL
descriptor_custom_t tm_epoch_descriptor
Time Library Epoch Descriptor.
Detailed Description
Time related function implementations.
See time.h for usage documentation. Implementation documentation should be added to this file as some point.
See also
time.h
Definition in file time.c.
Function Documentation
tm_check_invalid_rtime()
uint8_t tm_check_invalid_rtime (tm_real_t * rtime)
Validate a tm_real_t instance.
Returns 0 for valid tm_real_t, non-zero for out of bounds.
Parameters
rtime Pointer to the tm_rtime_t to validate.
Definition at line 134 of file time.c.
tm_clear_rdelta()
void tm_clear_rdelta (tm_rdelta_t * rdelta)
Clear a tm_rdelta_t instance.
Parameters
rdelta Pointer to the time_delta_t to clear.
Definition at line 124 of file time.c.
Referenced by tm_rdelta_from_sdelta().
tm_clear_rtime()
void tm_clear_rtime (tm_real_t * rtime)
Clear a tm_real_t instance.
Parameters
rtime Pointer to the time_real_t to clear.
Definition at line 112 of file time.c.
tm_clear_sdelta()
void tm_clear_sdelta (tm_sdelta_t * sdelta)
Clear a tm_sdelta_t instance.
Parameters
sdelta Pointer to the time_sdelta_t to clear.
Definition at line 107 of file time.c.
tm_clear_stime()
void tm_clear_stime (tm_system_t * stime)
Clear a tm_system_t instance.
Parameters
stime Pointer to the tm_system_t to clear.
Definition at line 102 of file time.c.
tm_init()
ucdm_addr_t tm_init (ucdm_addr_t ucdm_address)
Intitialize time library constructs.
The address provided to this function will be called TIME_BASE_ADDRESS for the purposes of this library, though EBS applications using the devicemap may choose to call it DMAP_TIME_BASE_ADDRESS instead. All other UCDM addresses discussed in this library will be referenced to this base address unless otherwise specified.
Definition at line 75 of file time.c.
tm_rdelta_from_sdelta()
void tm_rdelta_from_sdelta (tm_sdelta_t * sdelta, tm_rdelta_t * rdelta)
Convert a time difference in systick units into a real time difference.
Parameters
sdelta Pointer to the time difference in system time units.
rdelta Pointer to the tm_rdelta_t in which to store the result.
Definition at line 178 of file time.c.
References tm_clear_rdelta().
tm_register_epoch_change_handler()
void tm_register_epoch_change_handler (tm_epochchange_handler_t * handler)
Register a callback for changes to the epoch.
Use this if you are storing timestamps for any reason. If possible, invalidate your stored timestamps. If you need to retain that information, apply the provided delta.
If the change is not intended to be followed, the delta reported will be zero. In this case, the function should discard all timestamp information.
Note
This function should also be used to follow time sync where applicable.
Parameters
handler Pointer to the epoch change handler.
Definition at line 392 of file time.c.
tm_rtime_from_stime()
void tm_rtime_from_stime (tm_system_t * stime, tm_real_t * rtime)
Get the real time from a system timestamp against the current epoch.
If the current epoch is not set, does nothing.
Note
NOT IMPLEMENTED YET!
Todo:
Align to gmtime
Parameters
stime The system time (as a pointer to a tm_system_t instance)
rtime Pointer to the tm_real_t in which to store the result. represented by stime.
Definition at line 262 of file time.c.
tm_sdelta_from_rdelta()
void tm_sdelta_from_rdelta (tm_rdelta_t * rdelta, tm_sdelta_t * sdelta)
Convert a tm_rdelta_t instance into systick units.
Parameters
rdelta Pointer to the time difference in real time units.
sdelta Pointer to the tm_sdelta_t in which to store the result.
Definition at line 165 of file time.c.
tm_set_epoch()
void tm_set_epoch (tm_real_t * rtime, uint8_t follow)
Set the epoch time from an external real time source.
Note that for 'follow' to work, both the new epoch and the old one should be representable against the old epoch.
Because this function touches timestamps across the system, and the time variables are likely in an inconsistent state over the course of this operation, this function disables interrupts.
Parameters
rtime Pointer to the time_real_t in which the desired epoch is stored
follow Whether the system should try to adjust stored timestamps to the new epoch.
Definition at line 357 of file time.c.
References tm_stime_from_rtime().
tm_stime_from_rtime()
void tm_stime_from_rtime (tm_real_t * rtime, tm_system_t * stime)
Get a system timestamp from a real time, against the current epoch.
If the current epoch is not set, returns 0. Currently only supports epochs with frac = 0.
Todo:
Align to timegm.
Parameters
rtime The real time (as a pointer to a tm_real_t instance)
stime Pointer to the tm_system_t in which to store the result.
Definition at line 216 of file time.c.
Referenced by tm_set_epoch().
Variable Documentation
tm_epoch_descriptor
descriptor_custom_t tm_epoch_descriptor
Initial value:
= {NULL, DESCRIPTOR_TAG_TIME_EPOCH,
    sizeof(tm_real_t), DESCRIPTOR_ACCTYPE_PTR, {&tm_epoch}}
Time Library Epoch Descriptor.
Definition at line 54 of file time.c.